C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(-1,2,-2)*Gamma(-1,4,-3)*ProjM(-3,3)*ProjM(-2,1)
C     
      SUBROUTINE FFFF3_0(F1, F2, F3, F4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 F1(*)
      COMPLEX*16 TMP6
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP
      COMPLEX*16 F4(*)
      TMP6 = (F1(3)*F3(4)*(F4(6)*F2(5)-F4(5)*F2(6))+F1(4)*F3(3)*(F4(5)
     $ *F2(6)-F4(6)*F2(5)))
      VERTEX = COUP*(-2D0 * CI * TMP6)
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(-1,2,-2)*Gamma(-1,4,-3)*ProjM(-3,3)*ProjM(-2,1)
C     
      SUBROUTINE FFFF3_4_8_9_0(F1, F2, F3, F4, COUP1, COUP2, COUP3,
     $  COUP4,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP2
      COMPLEX*16 TMP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 COUP1
      COMPLEX*16 F3(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP4
      COMPLEX*16 COUP3
      COMPLEX*16 F4(*)
      CALL FFFF3_0(F1,F2,F3,F4,COUP1,VERTEX)
      CALL FFFF4_0(F1,F2,F3,F4,COUP2,TMP)
      VERTEX = VERTEX + TMP
      CALL FFFF8_0(F1,F2,F3,F4,COUP3,TMP)
      VERTEX = VERTEX + TMP
      CALL FFFF9_0(F1,F2,F3,F4,COUP4,TMP)
      VERTEX = VERTEX + TMP
      END


