ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MP,MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MB
     $ ,MDL_MH

      COMMON/MASSES/ MDL_MP,MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MB,MDL_MH


      DOUBLE PRECISION MDL_WH1,MDL_WTAU,MDL_WW,MDL_WT,MDL_WZ,MDL_WH

      COMMON/WIDTHS/ MDL_WH1,MDL_WTAU,MDL_WW,MDL_WT,MDL_WZ,MDL_WH


      DOUBLE COMPLEX GC_4, GC_71, GC_79, GC_80, GC_121, GC_125, GC_126
     $ , GC_127, GC_128, GC_143

      COMMON/COUPLINGS/ GC_4, GC_71, GC_79, GC_80, GC_121, GC_125,
     $  GC_126, GC_127, GC_128, GC_143

