ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of EWdim6'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_71 = ', GC_71
      WRITE(*,2) 'GC_79 = ', GC_79
      WRITE(*,2) 'GC_80 = ', GC_80
      WRITE(*,2) 'GC_121 = ', GC_121
      WRITE(*,2) 'GC_125 = ', GC_125
      WRITE(*,2) 'GC_126 = ', GC_126
      WRITE(*,2) 'GC_127 = ', GC_127
      WRITE(*,2) 'GC_128 = ', GC_128
      WRITE(*,2) 'GC_143 = ', GC_143
