ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SM4fLL_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_27 = ', GC_27
      WRITE(*,2) 'GC_28 = ', GC_28
      WRITE(*,2) 'GC_35 = ', GC_35
      WRITE(*,2) 'GC_36 = ', GC_36
      WRITE(*,2) 'GC_46 = ', GC_46
      WRITE(*,2) 'GC_54 = ', GC_54
      WRITE(*,2) 'GC_58 = ', GC_58
      WRITE(*,2) 'GC_61 = ', GC_61
